# Generated by Django 5.1.1 on 2024-09-29 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField(blank=True, default=None, help_text='Introduce tu fecha de nacimiento.', null=True, verbose_name='Fecha de Nacimiento')),
                ('imagen_usuario', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=50, unique=True)),
                ('descripcion_producto', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_pedido', models.TextField(blank=True, null=True)),
                ('precio_pagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pedido', models.DateField(auto_now_add=True)),
                ('fecha_entregado', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En progreso'), ('TERMINADO', 'Terminado')], default='PENDIENTE', max_length=20)),
                ('imagen_producto', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.perfil')),
            ],
        ),
    ]
